version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.21.0
    ports:
      - "${MLFLOW_PORT}:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns
