ARG TF_IMAGE

FROM ${TF_IMAGE}

WORKDIR /workspace
USER root

COPY apt-packages.txt .
RUN apt-get update && \
    grep -vE '^\s*#|^\s*$' apt-packages.txt | xargs apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir --ignore-install -r requirements.txt

COPY src /workspace/src

WORKDIR /workspace

CMD ["python", "-m", "{{package_name}}.train"]
